apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-2-deployment
spec:
  template:
    metadata:
      name: fastapi-2-pod
      labels:
        app: fastapi-2-pod
    spec:
      containers:
        - name: fastapi-container
          image: fastapi-app:cuda
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: fastapi-2-configmap
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1
            failureThreshold: 30
            initialDelaySeconds: 1
  # replicas: 6
  selector:
    matchLabels:
      app: fastapi-2-pod