apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-2-deployment
spec:
  template:
    metadata:
      name: fastapi-2-pod
      labels:
        app: fastapi-2-pod
    spec:
      containers:
        - name: fastapi-container
          image: fastapi-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: fastapi-2-configmap
  replicas: 6
  selector:
    matchLabels:
      app: fastapi-2-pod