apiVersion: v1
kind: Pod
metadata:
  name: pod-fastapi-2
  labels:
    app: fastapi-2
spec:
  containers:
    - name: fastapi-container
      image: fastapi-app
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80 
      envFrom:
        - configMapRef:
            name: fastapi-2-configmap